### PR TITLE
Skip cleanup hook if there are no tests. More verbose logging. Moved to package.

### PR DESCRIPTION
**Pull request by 0xRoch**
@ezh 

cc----

I moved plugin to package namespace. Debugger and code validator of the Eclipse is more friendly for standard layout. Sure that other development environments will more friendly too.

Also I added more verbose logging. It is not nice if SBT hangs without any messages on intermediate subproject without tests.

Also add condition that skip cleanup if there are no tests.

If there are no tests, now it looks like:

> scct-test:test
> [debug] 
> [debug] Initial source changes: 
> [debug] removed:Set()
> ...
> [debug] Subclass fingerprints: Stream((org.scalatest.Suite,false,org.scalatest.tools.ScalaTestFramework$$anon$1@2f32d1f2), ?)
> [debug] Annotation fingerprints: Stream((org.scalatest.WrapWith,false,org.scalatest.tools.ScalaTestFramework$$anon$2@31757f13), ?)
> [debug] scct: [Digi-Lib] No tests found. Skip SCCT setup hook.
> [debug] scct: [Digi-Lib] No tests found. Skip SCCT cleanup hook.
> [info] No tests to run for scct-test:test
> [success] Total time: 0 s, completed 19.05.2013 8:21:14
> And if there are tests:

[info] Passed: : Total 9, Failed 0, Errors 0, Passed 9, Skipped 0
[debug] scct: [Digi-Lib] Waiting for coverage report generation.
scct: [Digi-Lib] Generating coverage report.
[debug] scct: [Digi-Lib] Cleanup SCCT environment
[debug] Passed tests:
If you are not interested in theres changes please give me a note.

Thank you,
Alexey

---

https://github.com/mtkopone/sbt-scct/pull/4

### CODE REVIEW

**Comment by 0xRoch** [comment]
@ezh I was doing some testing related to https://github.com/SCCT/sbt-scct/pull/14 . Any idea why testSetup() is not executed when I run scct-test:test ?

**Comment by ezh** [comment]
I clone code but it is useless.
I suspect that it would wonderful to add scripted test with non working example. Something like https://github.com/digimead/sbt-site-manager/tree/master/src/sbt-test/site-manager/simple. Please add initial sketch. I will help you to complete scripted test configuration when will catching a bug.

It is very sad that you drop package namespace. Eclipse users are lost ability to use debugger with the plugin code :-( Are there any reasons or code conventions?

**Comment by ezh** [comment]
Also could you move addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.1") to you private sbt configuration? IMHO there may be people that like eclipse :-), ensime or raw editor. If anyone would add his favorite building/publishing plugins to the public config then there primary one will be a bit overloaded.

**Comment by 0xRoch** [comment]
@ezh Ok I'll start an initial sketch.
Regarding the package namespace I did not drop it I'll open a new issue about it, I just rolled it back for now because it required to add it when importing the settings like : `sbt.scct.ScctPlugin.instrumentSettings`.
If it's the only way we can do that we will do it in a new version to avoid breaking existing users apps.
About the sbt-idea conf you are right I'll remove it.

**Comment by 0xRoch** [comment]
@ezh concerning the non-working example check-out https://github.com/SCCT/scctSample I have modified build.sbt to exclude some packages : `ScctPlugin.scctExcludePackages in ScctPlugin.ScctTest := "Reverse*,views.html"`.
As you can see on the travis build : https://travis-ci.org/SCCT/scctSample/builds/13689424 we never get the `Prepare SCCT environment at ...` log.

**Comment by ezh** [comment]
@D-Roch Solved ;-)

You forgot turn on debug level ;-) With **logLevel := Level.Debug** everything fine

[debug] scct: [scctSample] Prepare SCCT environment at /home/ezh/projects/scct/scctSample/target/scala-2.10/scct-test-classes/scct.properties
[debug] Running TaskDef(IntegrationSpec, sbt.SubclassFingerprintWrapper@4629b46a, false, [SuiteSelector])
[debug] Running TaskDef(ApplicationSpec, sbt.SubclassFingerprintWrapper@4629b46a, false, [SuiteSelector])
[info] ApplicationSpec
[info] Application should
[info] + send 404 on a bad request
[info] + render the index page
[info] Total for specification ApplicationSpec
[info] Finished in 15 ms
[info] 2 examples, 0 failure, 0 error
[error] c.g.h.h.HtmlPage - Error loading JavaScript from [http://localhost:19001/assets/javascripts/jquery-1.9.0.min.js].
java.io.IOException: Unable to download JavaScript from 'http://localhost:19001/assets/javascripts/jquery-1.9.0.min.js' (status 404).
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1125) ~[htmlunit-2.12.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1059) ~[htmlunit-2.12.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:399) [htmlunit-2.12.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:260) [htmlunit-2.12.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:276) [htmlunit-2.12.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:676) [htmlunit-2.12.jar:2.12]
[info] IntegrationSpec
[info] Application should
[info] + work from within a browser
[info] Total for specification IntegrationSpec
[info] Finished in 15 ms
[info] 1 example, 0 failure, 0 error
[debug] scct: [scctSample] Waiting for coverage report generation.
scct: [scctSample] Generating coverage report.
[debug] scct: [scctSample] Cleanup SCCT environment
[debug] Summary for specs2 not available.
[debug] Summary for JUnit not available.
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3

**Comment by 0xRoch** [comment]
@ezh ahah yeah that was dumb ! sorry about that ! :+1:

**Pull request merged**
